import {
  WIDGET_SETTINGS_DEFAULT_MAIN_COLOR,
  WIDGET_SETTINGS_DEFAULT_PALETTE,
  WidgetSettingsChatRenderMode,
  WidgetSettingsLauncherType,
  WidgetSettingsVoiceRenderMode,
  WidgetSettingsWidgetPosition,
  WidgetSettingsWidgetType,
} from '@voiceflow/dtos-interact';
import { ChatPersistence } from '@voiceflow/voiceflow-types/build/cjs/version';

import type { ChatWidgetSettings } from '@/types/settings';

export const DEFAULT_WIDGET_SETTINGS: ChatWidgetSettings = {
  type: WidgetSettingsWidgetType.CHAT,

  chat: {
    voiceInput: true,
    voiceOutput: true,

    renderMode: WidgetSettingsChatRenderMode.WIDGET,

    headerImage: {
      enabled: true,
    },
    agentImage: {
      enabled: true,
    },
    banner: {
      enabled: true,
      title: 'Your AI agent',
      description: 'How can I help you today?',
    },
    placeholderText: 'Message...',
    aiDisclaimer: {
      enabled: true,
      text: 'Generated by AI, double-check for accuracy.',
    },
    handoffToAgentImageURL: '',
  },
  voice: {
    renderMode: WidgetSettingsVoiceRenderMode.FULL,
    content: {
      callToActionText: 'How can I help you?',
      startButtonText: 'Start a call',
      listeningText: 'Listening',
      talkingText: 'Talk to interrupt',
      endButtonText: 'End',
    },
  },
  common: {
    fontFamily: 'UCity Pro',
    launcher: {
      text: 'Your text',
      type: WidgetSettingsLauncherType.ICON,
    },
    poweredBy: true,
    footerLink: {
      enabled: true,
      text: 'Privacy',
    },
    position: WidgetSettingsWidgetPosition.RIGHT,
    sideSpacing: '20',
    bottomSpacing: '20',
    primaryColor: {
      color: WIDGET_SETTINGS_DEFAULT_MAIN_COLOR,
      palette: WIDGET_SETTINGS_DEFAULT_PALETTE,
    },
    persistence: ChatPersistence.LOCAL_STORAGE,
  },
  stylesheet: '',
  extensions: [],
};
