import { CARD_WIDTH } from '@/components/Card/styled';

import { CAROUSEL_GUTTER_WIDTH } from './styled';

export const CARD_WITH_BORDER_WIDTH = CARD_WIDTH + 2;
export const PREVIOUS_CONTROL_BOUNDARY = CARD_WITH_BORDER_WIDTH / 3;
export const NEXT_CONTROL_BOUNDARY = CARD_WITH_BORDER_WIDTH + CAROUSEL_GUTTER_WIDTH + PREVIOUS_CONTROL_BOUNDARY;
export const CARD_WITH_GUTTER_WIDTH = CARD_WITH_BORDER_WIDTH + CAROUSEL_GUTTER_WIDTH;
