import { ChatConfig } from '@voiceflow/react-chat';
import type { ChatWidgetSettings } from '@voiceflow/react-chat/build/types';

export const ASSISTANT: ChatWidgetSettings = {
  type: 'voice',
  chat: {
    voiceInput: true,
    voiceOutput: true,
    renderMode: 'widget',
    headerImage: {
      enabled: true,
    },
    agentImage: {
      enabled: true,
    },
    banner: {
      enabled: true,
      title: 'Your AI agent',
      description: 'How can I help you today?',
    },
    placeholderText: 'Message...',
    aiDisclaimer: {
      enabled: true,
      text: 'Generated by AI, double-check for accuracy.',
    },
    handoffToAgentImageURL: '',
  },
  common: {
    fontFamily: 'UCity Pro',
    launcher: {
      text: 'Your text',
      type: 'both',
    },
    poweredBy: true,
    footerLink: {
      enabled: true,
    },
    position: 'right',
    sideSpacing: '20px',
    bottomSpacing: '20px',
    primaryColor: {
      color: '#397DFF',
      palette: {
        50: '#E7F5FD',
        100: '#C6E4FB',
        200: '#A2D2FA',
        300: '#87BFFB',
        400: '#659FFD',
        500: '#397DFF',
        600: '#2F68DB',
        700: '#264EB4',
        800: '#1C368E',
        900: '#0F1E61',
      },
    },
    persistence: 'localStorage',
  },
  voice: {
    renderMode: 'full',
    content: {
      callToActionText: 'How can I help you?',
      startButtonText: 'Start a call',
      listeningText: 'Listening',
      talkingText: 'Talk to interrupt',
      endButtonText: 'End',
    },
  },

  stylesheet: '',
  extensions: [],
};

export const CONFIG = ChatConfig.parse({
  url: import.meta.env.VF_RUNTIME_URL ?? undefined,
  versionID: import.meta.env.VF_VERSION_ID,
  verify: {
    projectID: import.meta.env.VF_PROJECT_ID,
    versionID: import.meta.env.VF_VERSION_ID,
  },
  voice: {
    url: import.meta.env.VF_RUNTIME_API_URL,
    accessToken: import.meta.env.VF_ACCESS_TOKEN,
  },
});
